[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    links2004/WebSockets
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo
build_flags =
    -D CORE_DEBUG_LEVEL=1
